(source "elpa" "http://tromey.com/elpa/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(package "starter-kit")
(package "starter-kit-bindings")
(package "starter-kit-eshell")
(package "starter-kit-ruby")
(package "starter-kit-js")
(package "starter-kit-lisp")
(package "auto-complete")
(package "yasnippet")
(package "org")
(package "rinari")
(package "haml-mode")
(package "sass-mode")
(package "markdown-mode")
(package "coffee-mode")
(package "yaml-mode")
(package "gtags")
(package "ctags")
(package "rainbow-mode")
(package "project-mode")
(package "ntcmd")
(package "minimap")
(package "twilight-theme")
